version: '3'
services:
  backend:
    build: ./todo-app/back-end/
    image: todobackend
    ports:
      - 3001:3001
  frontend:
    build: ./todo-app/front-end/
    image: todofrontend
    ports:
      - 3000:3000
    depends_on:
      - todobackend
    environment:
      - REACT_APP_API_HOST=todobackend
  tests:
    build: ./todo-app/tests/
    image: todotests
    depends_on:
      - todobackend
      - todofrontend
    environment:
      - FRONT_HOST=todofrontend
      - FRONT_PORT=3000
